from .pre import pre_handler
from .b30 import b30_handler
from .assets_update import assets_update_handler
from .bind import bind_handler
from .info import info_handler
from .recent import recent_handler
from .best import best_handler
from .help import help_handler
from .random import random_handler
from .song import song_handler
from .preview import preview_handler
from .defualt import default_handler
